name: CI
on:
- push
- pull_request
jobs:

  main:
    strategy:
      matrix:
        include:
        - os: ubuntu-18.04
        - os: ubuntu-20.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - name: set up Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
    - name: set up APT
      run: |
        printf '\n\nPackage: *\nPin: release o=Ubuntu\nPin-Priority: 9999\n' | sudo tee -a /etc/apt/preferences
        printf 'Apt::Install-Recommends "false";\n' | sudo tee -a /etc/apt/apt.conf
        sudo apt-get update
    - name: apt install deps
      run:
        sudo apt-get install -y
          docbook-xml
          docbook-xsl
          gettext
          libxml2-utils
          xsltproc
    - name: install nose
      run: |
        python -m pip install nose
    - name: run tests
      run: |
        python -m nose --with-doctest --verbose lib/varietes.py
    - name: install
      run: |
        python setup.py install --user
    - name: check docs
      run: |
        python -m pip install docutils
        dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
        xmllint --nonet --noout --valid doc/*.xml
        private/check-rst
    - name: clean
      run: |
        python setup.py clean -a
    - name: run pydiatra
      run: |
        python -m pip install pydiatra
        python -m pydiatra -v .
    - name: run post-install checks
      run: |
        cd /
        command -v djvusmooth
        export MANPATH=/home/runner/.local/share/man MANWIDTH=80
        man 1 djvusmooth | grep -A 10 -w DJVUSMOOTH

  pypi:
    runs-on: ubuntu-latest
    steps:
    - name: check for namesquatting
      run: |
        set +e
        curl -fsS https://pypi.org/simple/djvusmooth/
        [ $? -eq 22 ] || exit 1

# vim:ts=2 sts=2 sw=2 et
